#!/bin/bash

private_repo='false'
commit_message='initial add'
release='false'
tf_workspace='false'
gh_description=''

print_usage() { 
  printf "Usage: Creates new Github repo in ${PWD}" 
}

while getopts 'pm:r:td:' flag; do
  case "${flag}" in
    p) private_repo='true' ;;
    m) commit_message="${OPTARG}" ;;
    r) release="${OPTARG}" ;;
    t) tf_workspace='true' ;;
    d) gh_description="${OPTARG}" ;;
    *) print_usage
       exit 1 ;;
  esac
done


REPO=$(pwd| awk -F/ '{ print $NF }')
cd $(dirname ${0})
terraform init
terraform apply -auto-approve -var repo=${REPO} -var description="${gh_description}" -var private=${private_repo}
output=$(terraform output)
mkdir ~/repo_init/${REPO}
mv ~/repo_init/terraform.tfstate* ~/repo_init/${REPO}
cd -
rm .gitignore LICENSE README.md || echo
git init
git remote add origin git@github.com:${TF_VAR_github_organization}/${REPO}
git pull origin master
git add .
git commit -m "${commit_message}"
git push -u origin master

echo ${output}

if [ ${release} != 'false ]
then
  git tag -a ${release} -m "${commit_message}"
  git push -u origin ${release}
fi
 
if [ ${tf_workspace} == 'true' ]
then
  tfe workspace new -tfe-workspace ${REPO} -vcs-id ${TF_VAR_github_organization}/${REPO}
  tfe pushconfig -tfe-workspace ${REPO}
fi
